### ISSUE TITLE
Datagrid setColModel

### ISSUE THREAD

**Issue by d-silva** [thrace-project/datagrid-bundle#15]
Hi,

How can i get date attr string from a DateTime column to be displayed?

I was limiting thrace/datagrid-bundle to v1.1.1 but i noticed that were Added DateTime event subscriber and related stuff so i updated composer to 1.1.*@dev.

I tryed so many diferent ways and still have [object Object] displaying in date column like im showing in the screenshot.

![screenshot](https://cloud.githubusercontent.com/assets/10325736/7834649/51c23c10-0469-11e5-97e6-24b8d912c548.png)

Thank you in advance

**Comment by zender** [comment]
This bundle is deprecated!!!
